export { ApiError, setRefreshHandler, demoRequest } from '@/lib/api/client'
export * from '@/lib/api/types'
export * from '@/lib/api/mappers'
export { authApi } from '@/lib/api/auth'
export { appointmentsApi } from '@/lib/api/appointments'
export { barbersApi } from '@/lib/api/barbers'
export { servicesApi } from '@/lib/api/services'
export { customersApi } from '@/lib/api/customers'
export { salonApi, statisticsApi } from '@/lib/api/statistics'
export { publicApi } from '@/lib/api/public'
export type { PublicSalon, PublicService, PublicBarber, PublicBarberWithSalon, PublicBarberSchedule, PublicAvailabilitySlot } from '@/lib/api/public'
export { supportApi, notificationsApi } from '@/lib/api/statistics'
